from clases.creatures import Creature
from clases.spells import Spell

mesopotamia_empire = [Spell(8, "Epidemic", "Destroy ALL minions", -32),
                      Creature(1, "City Gate Guard", 3, 1, "Guard", "ancient", -104),
                      Spell(3, "Ancient Tactics", "Draw 3 cards deal 3 damage to your kingdom", -105),
                      Creature(1, "Mesopotamia Scholar", 1, 2, "Draw a card Deal 2 damage to your kingdom", "ancient",
                               -106),
                      Creature(9, "King Saragon of Akkad", 7, 9,
                               "Give all ancients +2/+2 your knigdom can't take damage", "ancient", -107),
                      Creature(2, "Military Guard", 4, 2, "Guard Deal 2 damage to your kingdom", "ancient", -108),
                      Creature(1, "Lu", 2, 3, "Deal 2 damage to your kingdom", "ancient", -109),
                      Spell(4, "Mercenaries Reinforcements", "Deal 2-4 damage and summ that many Man at arms", -110),
                      Creature(5, "Assyrian Horserider", 7, 5, "Charge discard 2 cards from your hand", "ancient",
                               -111),
                      Spell(6, "Tactical Coordination", "When you discard or use this draw 3 cards", -112),
                      Creature(9, "Turtanu", 9, 3, "Guard Desperate Summon 3 City Gate Guards", "ancient", -113),
                      Creature(3, "Prisoner of War", 4, 3, "If you discard this summon it", "ancient", -114),
                      ]
mesopotamia_show = [Spell(8, "Epidemic", "Destroy ALL minions", -32),
                    Creature(1, "City Gate Guard", 3, 1, "Guard", "ancient", -104),
                    Spell(3, "Ancient Tactics", "Draw 3 cards deal 3 damage to your kingdom", -105),
                    Creature(1, "Mesopotamia Scholar", 1, 2, "Draw a card Deal 2 damage to your kingdom", "ancient",
                             -106),
                    Creature(9, "King Saragon of Akkad", 7, 9, "Give all ancients +2/+2 your knigdom can't take damage",
                             "ancient", -107),
                    Creature(2, "Military Guard", 4, 2, "Guard Deal 2 damage to your kingdom", "ancient", -108),
                    Creature(1, "Lu", 2, 3, "Deal 2 damage to your kingdom", "ancient", -109),
                    Spell(4, "Mercenaries Reinforcements", "Deal 2-4 damage and summ that many Man at arms", -110),
                    Creature(5, "Assyrian Horserider", 7, 5, "Charge discard 2 cards from your hand", "ancient", -111),
                    Spell(6, "Tactical Coordination", "When you discard or use this draw 3 cards", -112),
                    Creature(9, "Turtanu", 9, 3, "Guard Desperate Summon 3 City Gate Guards", "ancient", -113),
                    Creature(3, "Prisoner of War", 4, 3, "If you discard this summon it", "ancient", -114),
                    ]