from clases.creatures import Creature
from clases.spells import Spell

cards_for_mongol = [Spell(3, "Volley", "Deal 2 damage to all enemies", -5),
                    Spell(1, "Arrow shot", "Deal 2 damage to a enemy", -6),
                    Creature(2, "Hunting dog", 1, 2, "Charge", "animal", -30),
                    Spell(3, "Horse riding lessons", "Give a friendly creature charge and +2 attack",
                          -19),
                    Creature(3, "Hunter", 3, 2, "Summon a 1/1 Dog", "worker", -44),
                    Creature(3, "Rider", 2, 3, "Charge", "soldier", -45),
                    Spell(2, "Call of the Khan", "Draw a card if it has Charge reduce the cost to 0", -46),
                    Creature(3, "Negotiator", 1, 1, "Give your hand +1/+1 and draw a animal", "worker", -57),
                    Spell(3, "Horse raiding shot", "Deal 2 damage and draw a card", -58),
                    Creature(2, "Wild Horse", 2, 1, "Draw a charge card", "animal", -59),
                    Spell(3, "For the Khan", "Give all your minions +1/+0 and Charge", -67),
                    Creature(9, "Jochi", 8, 8, "Charge", "soldier", -78),
                    Spell(3, "Animal Battle Companion", "Summon a random war animal", -92),
                    Creature(6, "Khevtuul", 5, 7, "Desperate summon 2 2/2 Night Watchers", "soldier", -93),
                    Spell(8, "War Pack", "Summon all war animals", -94),
                    Creature(4, "Animal Tamer", 3, 4, "Give a friendly animal +2/+2 and guard", "worker", -95),
                    Creature(4, "Mother Wolf", 3, 3, "Desperate summ 2 1/1 Wolf Pup", "animal", -96),
                    Creature(1, "Domestic cat", 1, 1, "Summon a 1/1 Wild Cat", "animal", -97),
                    Creature(2, "Goat", 1, 1, "Desperate summon a 3/2 Hungry Wolf", "animal", -98),
                    Spell(4, "Tag Team", "Dela 3 damage to a minion summ a 3/3 Hunting dog", -99),
                    Creature(3, "Big Game Beast", 3, 3, "Desperate draw an animal", "animal", -130),
                    Creature(1, "Lure animal", 1, 1, "Desperate add a random animal to your hand", "animal", -152),
                    ]
cards_for_mongol_empire = [Spell(3, "Volley", "Deal 2 damage to all enemies", -5),
                           Spell(1, "Arrow shot", "Deal 2 damage to a enemy", -6),
                           Creature(2, "Hunting dog", 1, 2, "Charge", "animal", -30),
                           Spell(3, "Horse riding lessons", "Give a friendly creature charge and +2 attack",
                                 -19),
                           Creature(3, "Hunter", 3, 2, "Summon a 1/1 Dog", "worker", -44),
                           Creature(3, "Rider", 2, 3, "Charge", "soldier", -45),
                           Spell(2, "Call of the Khan", "Draw a card if it has Charge reduce the cost to 0", -46),
                           Creature(3, "Negotiator", 1, 1, "Give your hand +1/+1 and draw a animal", "worker", -57),
                           Spell(3, "Horse raiding shot", "Deal 2 damage and draw a card", -58),
                           Creature(2, "Wild Horse", 2, 1, "Draw a charge card", "animal", -59),
                           Spell(3, "For the Khan", "Give all your minions +1/+0 and Charge", -67),
                           Creature(9, "Jochi", 8, 8, "Charge", "soldier", -78),
                           Spell(3, "Animal Battle Companion", "Summon a random war animal", -92),
                           Creature(6, "Khevtuul", 5, 7, "Desperate summon 2 2/2 Night Watchers", "soldier", -93),
                           Spell(8, "War Pack", "Summon all war animals", -94),
                           Creature(4, "Animal Tamer", 3, 4, "Give a friendly animal +2/+2 and guard", "worker", -95),
                           Creature(4, "Mother Wolf", 3, 3, "Desperate summ 2 1/1 Wolf Pup", "animal", -96),
                           Creature(1, "Domestic cat", 1, 1, "Summon a 1/1 Wild Cat", "animal", -97),
                           Creature(2, "Goat", 1, 1, "Desperate summon a 3/2 Hungry Wolf", "animal", -98),
                           Spell(4, "Tag Team", "Dela 3 damage to a minion summ a 3/3 Hunting dog", -99),
                           Creature(3, "Big Game Beast", 3, 3, "Desperate draw an animal", "animal", -130),
                           Creature(1, "Lure animal", 1, 1, "Desperate add a random animal to your hand", "animal",
                                    -152),
                           ]
mongols_hordes = [Creature(6, "War elephant", 5, 4,
                           "While this is on the field your creatures have +1 attack", "animal", 1900),
                  Spell(3, "Animal Battle Companion", "Summon a random war animal", 1901),
                  Creature(3, "Negotiator", 1, 1, "Give your hand +1/+1 and draw a animal", "worker", 1902),
                  Spell(1, "Arrow shot", "Deal 2 damage to a enemy", 1903),
                  Creature(2, "Hunting dog", 1, 2, "Charge", "animal", 1904),
                  Spell(8, "War Pack", "Summon all war animals", 1905),
                  Creature(4, "Animal Tamer", 3, 4, "Give a friendly animal +2/+2 and guard", "worker", 1906),
                  Creature(2, "Wild Horse", 2, 1, "Draw a charge card", "animal", 1907),
                  Creature(3, "Tournament Horserider", 1, 2, "Charge Armored", "knight", 1908),
                  Creature(2, "Goat", 1, 1, "Desperate summon a 3/2 Hungry Wolf", "animal", 1909),
                  Creature(6, "Joan of Arc", 2, 2, "Desperate Summ 7/8 Saint Joan of Arc with charge and armored",
                           "soldier", 1910),
                  Creature(2, 'Page', 1, 1, "Draw a card", "knight", 1911),
                  Creature(3, "Rider", 2, 3, "Charge", "soldier", 1912),
                  Creature(3, "Rider", 2, 3, "Charge", "soldier", 1913),
                  Creature(5, "Mounted Knight", 4, 4, "Charge", "knight", 1914),
                  Creature(5, "Mounted Knight", 4, 4, "Charge", "knight", 1915),
                  Spell(4, "Tag Team", "Dela 3 damage to a minion summ a 3/3 Hunting dog", 1916),
                  Creature(3, "Negotiator", 1, 1, "Give your hand +1/+1 and draw a animal", "worker", 1917),
                  Spell(5, "Kill", "Kill an enemy minion", 1918),
                  Spell(5, "Kill", "Kill an enemy minion", 1919),
                  Spell(2, "Call of the Khan", "Draw a card if it has Charge reduce the cost to 0", 1920),
                  Creature(2, "Wild Horse", 2, 1, "Draw a charge card", "animal", 1921),
                  Creature(4, "Mother Wolf", 3, 3, "Desperate summ 2 1/1 Wolf Pup", "animal", 1922),
                  Spell(8, "War Pack", "Summon all war animals", 1923),
                  Creature(4, "Animal Tamer", 3, 4, "Give a friendly animal +2/+2 and guard", "worker", 1924),
                  Spell(3, "Animal Battle Companion", "Summon a random war animal", 1925),
                  Creature(4, "Mother Wolf", 3, 3, "Desperate summ 2 1/1 Wolf Pup", "animal", 1926),
                  Creature(9, "Jochi", 8, 8, "Charge", "soldier", 1927),
                  Creature(6, "Khevtuul", 5, 7, "Desperate summon 2 2/2 Night Watchers", "soldier", 1928),
                  Creature(2, 'Page', 1, 1, "Draw a card", "knight", 1929),
                  ]