from ITschool_projects.battle_resources.clases.creatures import Creature
from ITschool_projects.battle_resources.clases.spells import Spell

starter_deck = [Creature(1, "Peasant", 1, 1, "", 1),
                Creature(1, "Peasant", 1, 1, "", 2),
                Creature(1, "Peasant", 1, 1, "", 3),
                Creature(1, "Peasant", 1, 1, "", 4),
                Creature(1, "Peasant", 1, 1, "", 5),
                Creature(1, "Peasant", 1, 1, "", 6),
                Creature(0, "Andras", 99, 99, "", 1000)]

demo_deck = [Creature(1, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 1),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 2),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 3),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 4),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 5),
             Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 10),
             Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 1),
             Creature(4, "Mounted Knight", 4, 4, "Charge", 15),
             Creature(4, "Mounted Knight", 4, 4, "Charge", 16),
             ]

test_deck = [Creature(1, 'Hospitaller Knight', 5, 4, "Heal 2 a friendly soldier", 6),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal 2 a friendly soldier", 7),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal 2 a friendly soldier", 8),
             Creature(1, 'Hospitaller Knight', 5, 4, "Heal 2 a friendly soldier", 9),
             Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 11),
             Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 12),
             Creature(4, "Mounted Knight", 4, 4, "Charge", 13),
             Creature(4, "Mounted Knight", 4, 4, "Charge", 14),
             Creature(1, 'Templar Knight', 10, 5, "Guard", 261),
             ]

knight_deck = [Creature(6, 'Templar Knight', 5, 5, "", 23),
               Creature(1, 'Page', 1, 1, "", 24),
               Creature(3, 'Squire', 1, 1, "", 25),
               Creature(3, 'Squire', 1, 1, "", 26),
               Creature(6, 'Templar Knight', 5, 5, "", 27),
               Creature(6, 'Templar Knight', 5, 5, "", 28),
               Creature(8, 'Hospitaller Knight', 8, 3, "", 29),
               Creature(8, 'Hospitaller Knight', 8, 3, "", 30),
               Creature(8, 'Hospitaller Knight', 8, 3, "", 31),
               Creature(7, 'Teutonic Knight', 6, 5, "", 32),
               Creature(7, 'Teutonic Knight', 6, 5, "", 33),
               Creature(9, "Two-handed Knight", 5, 5, "Kill an enemy soldier", 20),
               Creature(9, "Two-handed Knight", 5, 5, "Kill an enemy soldier", 21),
               Creature(9, "Two-handed Knight", 5, 5, "Kill an enemy soldier", 22),
               ]

knight_deck_official = [Creature(9, "Two-handed Knight", 5, 5, "Kill an enemy soldier", 251),
                        Creature(9, "Two-handed Knight", 5, 5, "Kill an enemy soldier", 252),
                        Creature(7, 'Teutonic Knight', 6, 5, "", 253),
                        Creature(7, 'Teutonic Knight', 6, 5, "", 254),
                        Creature(6, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 255),
                        Creature(6, 'Hospitaller Knight', 5, 4, "Heal +2 a friendly soldier", 256),
                        Creature(2, 'Squire', 2, 2, "", 257),
                        Creature(2, 'Squire', 2, 2, "", 258),
                        Creature(1, 'Page', 1, 1, "", 259),
                        Creature(1, 'Page', 1, 1, "", 260),
                        Creature(7, 'Templar Knight', 7, 5, "Guard", 261),
                        Creature(7, 'Templar Knight', 7, 5, "Guard", 262),
                        Creature(4, "Mounted Knight", 4, 4, "Charge", 263),
                        Creature(4, "Mounted Knight", 4, 4, "Charge", 264),
                        Spell(3, "Volley", "Deal 1 damage to all enemies", 265),
                        Spell(3, "Volley", "Deal 1 damage to all enemies", 266),
                        Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 267),
                        Spell(1, "Arrow shot", "Deal 1 damage to a enemy", 268),
                        Spell(5, "Kill", "Kill an enemy soldier", 269),
                        Spell(5, "Kill", "Kill an enemy soldier", 270),
                        ]
